### ISSUE TITLE
bounding box error

### ISSUE THREAD

**Issue by bpwl0121** [udacity/nd013-c1-vision-starter#3]
Hi,
https://github.com/udacity/nd013-c1-vision-starter/blob/c1e375fe933c20787b65ea11ab24c6e2ed87b453/download_process.py#L49

Waymo provides images in the 1920x1080 format 
But in the processing part the images are resized to 640x640 format but not for the bounding box
the bounding box should be resized and normalized in 1920x1080 

Pls update the code and the data in the workspace in Udacity
thanks!

**Comment by thomashossler** [comment]
good catch! This is now fixed.
