### ISSUE TITLE
Dockerfile unable to create container on local system. 

### ISSUE THREAD

**Issue by srikds** [udacity/nd013-c1-vision-starter#7]
I have built the image from Dockerfile as per the given commands. When i run 
docker run --gpus all -v <PATH TO LOCAL PROJECT FOLDER>:/app/project/ --network=host -ti project-dev bash on CMD. following error pops up:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

**Comment by thomashossler** [comment]
what's the output of the `nvidia-smi` command ?

**Comment by srikds** [comment]
![Capture](https://user-images.githubusercontent.com/83066072/134235080-3a78399a-f940-4fa5-a99d-f0be99939b5b.PNG)

**Comment by thomashossler** [comment]
The build has been tested on ubuntu 20.04 with cuda 11.2 and drivers 460.91.03. I would recommend experimenting with WSL.

**Comment by srikds** [comment]
What do you mean exactly when you say experimenting with wsl?

**Comment by srikds** [comment]
What do you mean exactly when you say experimenting with wsl??
